### ISSUE TITLE
improve the design of web page

### ISSUE THREAD

**Issue by victoriagjh** [victoriagjh/sentiment_analysis#13]
- [x] progress bar in main page
- [x] link to show the tool's documentation
- [x] more interactive visualization
- [x] timeline(make test file randomly date time)

**Comment by hollylululu** [comment]
Updated from 8/8 meeting:

- [ ] Compute three scores for each tool: tweet-level score, sentence-level average score, sentence-level majority voting score. 

- [ ] Display a BIG table that contains: ID, tweet, three scores for each tool. Compute the [kappa agreement ratio ](https://en.wikipedia.org/wiki/Cohen%27s_kappa) for the tools, order the rows of the table based on the consistency (i.e., the agreement ratio) - tweets with the highest consistency among the tools will be at the bottom of the table, and tweets with the lowest consistency among the tools will be at the top of the table. Use colors to mark the results (e.g., red for negative, green for positive).

- [ ] Combine expert mode and basic mode.

- [ ] Use navigation bar or segmentation or collapse function to separate the three sections: tool results and consistency table, surface metrics, and visualizations.
